### ISSUE TITLE
Issue #1 - Textarea will not populate with content from database when in "edit" mode.

### ISSUE THREAD

**Issue by mrrooijen** [80beans/wysihat-engine#1]
http://dl.getdropbox.com/u/261187/issue1.mov

Check it out.

  <% form_for @product do |f| %>
   <%= f.error_messages %>
   <p>
     <%= f.label :name %><br />
     <%= f.text_field :name %>
  </p>
   <p>
     <%= f.label :description %><br />
     <%= f.wysihat_editor :description, :buttons => [:bold, :italic, :underline, :image] %>
   </p>
   <p><%= f.submit "Submit" %></p>
  <% end %>

**Comment by mrrooijen** [comment]
Update:

I fixed this by adding doing the following:

  <%= f.wysihat_editor :description, :buttons => [:bold, :italic, :underline, :image], :value => @product.description %>

I'm not sure if this is how it should be? I'd assume it'd have to do it automatically with just the :description symbol.

**Comment by jeffkreeftmeijer** [comment]
This was most certainly a bug, which had to do with the structure of the lib/wysihat_engine.rb file. I'm not going to explain it all here, but I'd be happy to do so over email. You can also check out the commit (http://github.com/80beans/wysihat-engine/commit/67206077ffb2f822b7dedfc9d08635c3d6bcd9d4 ) to see what changed.

Thanks again for reporting :)
