### ISSUE TITLE
Error on installing on Heroku

### ISSUE THREAD

**Issue by digitalknk** [80beans/wysihat-engine#4]
I keep getting this error no matter what I do on heroku and my code. PLEASE HELP!

-----> Heroku receiving push

-----> Installing gem paperclip >= 2.3.1 from http://gemcutter.org, http://gems.rubyforge.org
       Successfully installed paperclip-2.3.1.1
       1 gem installed

-----> Installing gem wysihat-engine from http://gemcutter.org, http://gems.rubyforge.org
       ERROR:  Error installing wysihat-engine:
        wysihat-engine requires thoughtbot-paperclip (>= 2.3.1, runtime)

I can not go on with my push because it do not want to install it.

**Comment by jeffkreeftmeijer** [comment]
Hi Nerdrocket,

The gem dependency for paperclip was still pointing to the one on github, but it should've been pointing to the one on gemcutter. My bad.

I pushed a fix and updated the gem, so you should be able to install it now. Just update wysihat-engine and you'll be fine. :)

If you run into any more problems, be sure to let me know! :)
