### ISSUE TITLE
Wysihat not initializing properly when in ajax link_to_remote

### ISSUE THREAD

**Issue by materialvision** [80beans/wysihat-engine#5]
Maybe not a direct issue to report, but I could need some help using your great wysihat-engine in a project that populates a div element with the wysihat form through the link_to_remote ajax call. For some reason it does not work, just gives me a regular text-area form. I suspect it has to do with a lack for a window load event for the wysihatify? Maybe I could call this function directly from the ":complete" callback in the "link_to_remote"? A bit too hard for me to work through all the javascript code to find a workaround.

Any help greatly appreciated!
Best, Espen

**Comment by jeffkreeftmeijer** [comment]
Hi Espen,

First of all; thanks for your kind words. I don't think I completely understand your problem, I could use some code to go with it. :) Is it on Github? That'd make it easy for me to pull and see what's happening. :)
