### ISSUE TITLE
Which html tags are removed when text is saved?

### ISSUE THREAD

**Issue by materialvision** [80beans/wysihat-engine#9]
Hi. I ran into some problems today, trying to use the wysihat for rendering html pages (stored in a database) with advanced tags like "object" for quicktime, and "form" tags for some paypal-forms. Both of these are somehow removed when saving to the database (actually some of them are removed and some are kept, difficult to see a pattern). 

I haven´t managed to find out where exactly this sanitizing is happening in the wysihat.js (so that I could possibly disable it). 

Any ideas? 
Thanks again for a great gem.

**Comment by jeffkreeftmeijer** [comment]
I saw you created an issue ( http://github.com/josh/wysihat/issues/issue/14 ) for this on the WysiHat core issue tracker (which is a better place for these kind of questions), so I'm going to close this one. :)

:)
